# Generated by Django 5.1.1 on 2024-12-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dress_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='dress_rating',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
