# Generated by Django 5.1.1 on 2024-12-13 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dress_dress_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='catagory',
        ),
    ]
