# Generated by Django 5.1.1 on 2024-12-13 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_name_category_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dress',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
