# Generated by Django 5.1.1 on 2024-12-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
