# Generated by Django 5.1.1 on 2025-01-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_product_image_product_thumbnail_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail',
            new_name='product_image',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
