# Generated by Django 5.1.1 on 2025-01-10 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_product_product_image_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
