# Generated by Django 5.1.1 on 2025-01-10 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
