# Generated by Django 5.1.1 on 2025-01-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vendor',
            field=models.BooleanField(default=False),
        ),
    ]
