# Generated by Django 5.1.1 on 2025-01-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_product_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Excelent'), (3, 'Good'), (4, 'Average'), (5, 'Poor')], default=1),
        ),
    ]
