# Generated by Django 5.1.1 on 2025-01-25 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_product_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedby',
            name='user',
        ),
        migrations.AddField(
            model_name='orderedby',
            name='userprofile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
            preserve_default=False,
        ),
    ]
