# Generated by Django 5.1.1 on 2025-01-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_userprofile_total_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='products_uploaded',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
