# Generated by Django 5.1.1 on 2025-01-25 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_userprofile_products_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='no_of_sales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='products_uploaded',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
