# Generated by Django 5.1.1 on 2025-01-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_userprofile_no_of_sales_userprofile_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_rating',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Excelent'), (3, 'Good'), (4, 'Fair'), (5, 'Poor')], default=1),
        ),
    ]
