# Generated by Django 5.1.1 on 2025-01-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_product_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sold',
        ),
    ]
