# Generated by Django 5.1.1 on 2025-01-27 05:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
