# Generated by Django 5.1.1 on 2025-01-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_feedback_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedby',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
