"""
Django settings for test005 project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+041l6j3*bfa0p0@6x9pc&_@11%(bz7im-%q525a39uy8-6nzz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'payment',
    'mathfilters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'test005.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.base_context',
            ],
        },
    },
]




WSGI_APPLICATION = 'test005.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
		'default': {
        	'ENGINE' : 'django.db.backends.postgresql',
        	'NAME' : 'Django_store',	#db name
        	'USER' : 'Django',	#login name 
        	'PASSWORD' : 'django', 	#login password
    		}
	}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

import os
STATIC_URL = '/static/'		#javascript css ko lagi
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')

STATICFILES_DIR = {
    os.path.join(BASE_DIR , "luga/items_images")
}

MEDIA_ROOT =  os.path.join(BASE_DIR, 'app/')  #this is for the media file
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "rushalmanandhar@gmail.com" 
EMAIL_HOST_PASSWORD = "" 

ESEWA_ENV = "production"  # Change to "production" when deploying

if ESEWA_ENV == "sandbox":
    ESEWA_MERCHANT_ID = 'EPAYTEST'
    ESEWA_VERIFY_URL = 'https://uat.esewa.com.np/epay/main'
    ESEWA_VERIFY_API = 'https://uat.esewa.com.np/epay/transrec'
else:
    ESEWA_MERCHANT_ID = 'your_actual_merchant_id'
    ESEWA_VERIFY_URL = 'https://esewa.com.np/epay/main'
    ESEWA_VERIFY_API = 'https://esewa.com.np/epay/transrec'

ESEWA_SUCCESS_URL = 'http://127.0.0.1:8000/payment/success/'  # Update with your local testing domain
ESEWA_FAILURE_URL = 'http://127.0.0.1:8000/payment/failure/'


#_____________________________TIME ZONE________NEPAL_____________
TIME_ZONE = 'Asia/Kathmandu'
USE_TZ = True
# ______________________________________________________